package com.spring.basics;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        ApplicationContext applicationContext = new ClassPathXmlApplicationContext("context.xml");
        Restaurant restaurant = applicationContext.getBean("restaurant",Restaurant.class);
        Restaurant restaurant2 = applicationContext.getBean("restaurant2",Restaurant.class);
        restaurant.printDrink();
        restaurant2.printDrink();
        System.out.println(applicationContext.isPrototype("teaBean"));
    }
}
